version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocyclo:
      min-complexity: 80
    staticcheck:
      checks:
        - all
        - -ST1023 # var hasLonghorn bool = false is intentionally verbose
        - -QF1011 # same deal
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    presets:
      - std-error-handling
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - dupl
        path: cmd/*
    paths:
      - third_party$
      - builtin$
      - examples$
      - test/.*
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
