apiVersion: v1
kind: Service
metadata:
  name: {{ include "talos-operator.metricsServiceName" . }}
  labels:
    {{- include "talos-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
  selector:
    {{- include "talos-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
