---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - talos.rtl.de
  resources:
  - clusters
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - talos.rtl.de
  resources:
  - clusters/finalizers
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - talos.rtl.de
  resources:
  - clusters/status
  - nodes/status
  verbs:
  - get
  - patch
  - update
