package v1alpha1

import (
	"fmt"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Domain",type=string,JSONPath=`.spec.domain`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
// +kubebuilder:printcolumn:name="Kubernetes",type=string,JSONPath=`.spec.kubernetesVersion`
// +kubebuilder:printcolumn:name="ConfigInSync",type=string,JSONPath=`.status.conditions[?(@.type=="ClusterNodesInSync")].status`
// +kubebuilder:printcolumn:name="K8sInSync",type=string,JSONPath=`.status.conditions[?(@.type=="ClusterNodesKubernetesUpToDate")].status`
// +kubebuilder:printcolumn:name="Operation",type=string,JSONPath=`.status.operationStatus.type`
// +kubebuilder:printcolumn:name="Operation Phase",type=string,JSONPath=`.status.operationStatus.phase`
// +kubebuilder:printcolumn:name="Operation Age",type=date,JSONPath=`.status.operationStatus.lastTransitionTime`,description="Last transition time of the current operation"
// +kubebuilder:printcolumn:name="Next Maintenance Window",type=string,JSONPath=`.status.nextMaintenanceWindow`

// Cluster is the Schema for the clusters API
type Cluster struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty,omitzero"`

	// spec defines the desired state of Cluster
	// +required
	Spec ClusterSpec `json:"spec"`

	// status defines the observed state of Cluster
	// +optional
	Status ClusterStatus `json:"status,omitempty,omitzero"`

	// operation defines a requested operation on the Cluster
	// +optional
	Operation *ClusterOperation `json:"operation,omitempty,omitzero"`
}

// ClusterSpec defines the desired state of Cluster
type ClusterSpec struct {
	// KubernetesVersion is the desired Kubernetes version for the cluster.
	// If left empty, a default will be set by the operator.
	// +optional
	// +kubebuilder:validation:Pattern=`^(v\d+\.\d+\.\d+)?$`
	KubernetesVersion string `json:"kubernetesVersion"`

	// TalosVersionContract is the Talos version contract to target when generating configuration.
	// If left empty, will default to the current Talos version contract.
	// +optional
	// +kubebuilder:validation:Pattern=`^(v\d+\.\d+)?$`
	TalosVersionContract string `json:"talosVersionContract"`

	// Domain is the domain name suffix used for all nodes in the cluster.
	// The default control plane URL is also (meta.name + "." + spec.domain).
	// +required
	Domain string `json:"domain"`

	// SecretsRef is the name of the Secret containing the secrets.yaml of the cluster.
	// If left empty or the named secret doesn't exist, the secret will be generated by the operator.
	// +optional
	SecretsRef string `json:"secretsRef"`

	// Patches is a list of inline YAML / JSON patches to be applied to the Talos config for all nodes in the cluster.
	// +optional
	Patches []string `json:"patches,omitempty"`

	// ControlPlanePatches is a list of inline YAML / JSON patches to be applied to the Talos config for control plane nodes in the cluster.
	// +optional
	ControlPlanePatches []string `json:"controlPlanePatches,omitempty"`

	// WorkerPatches is a list of inline YAML / JSON patches to be applied to the Talos config for worker nodes in the cluster.
	// +optional
	WorkerPatches []string `json:"workerPatches,omitempty"`

	// PatchRefs is a list of references to ConfigMap resources containing patches to be applied to the Talos config for all nodes in the cluster.
	// +optional
	PatchRefs []PatchRef `json:"patchRefs,omitempty"`

	// ControlPlanePatchRefs is a list of references to ConfigMap resources containing patches to be applied to the Talos config for control plane nodes in the cluster.
	// +optional
	ControlPlanePatchRefs []PatchRef `json:"controlPlanePatchRefs,omitempty"`

	// WorkerPatchRefs is a list of references to ConfigMap resources containing patches to be applied to the Talos config for worker nodes in the cluster.
	// +optional
	WorkerPatchRefs []PatchRef `json:"workerPatchRefs,omitempty"`

	// Options contains settings to adjust the behavior of the Talos operator for this Cluster.
	// +optional
	Options ClusterOptions `json:"options,omitzero"`
}

// ClusterOptions define options for customizing the behavior of the Talos operator for this Cluster.
type ClusterOptions struct {
	// Maintenance defines options relating to the maintenance window feature.
	// +optional
	MaintenanceWindow ClusterMaintenanceWindow `json:"maintenanceWindow,omitzero"`

	// ArgoCDSecret defines options relating to the ArgoCD cluster secret generation feature.
	// +optional
	ArgoCDSecret ClusterArgoCDSecret `json:"argoCDSecret,omitzero"`

	// PhaseTimeout defines the maximum length that an operation phase may take before being
	// considered failed. This applies to all phases except Draining, the most notable of
	// which is the Verifying phase.
	// +optional
	// +kubebuilder:default="10m"
	PhaseTimeout string `json:"phaseTimeout,omitempty"`

	// DrainTimeout defines a timeout for drain operations performed by the operator.
	// +optional
	// +kubebuilder:default="20m"
	DrainTimeout string `json:"drainTimeout,omitempty"`

	// AutoBootstrap enables automatic cluster bootstrap when the cluster is ready.
	// When true (default), the operator will automatically bootstrap the cluster once
	// enough controlplane nodes are provisioned and ready to form a quorum.
	// When false, bootstrap must be manually triggered.
	// +optional
	// +kubebuilder:default=true
	AutoBootstrap *bool `json:"autoBootstrap,omitempty"`
}

// GetPhaseTimeout returns the PhaseTimeout as a time.Duration.
// Parsing errors return default values along with the error.
func (o ClusterOptions) GetPhaseTimeout() (time.Duration, error) {
	if o.PhaseTimeout == "" {
		o.PhaseTimeout = "10m"
	}
	duration, err := time.ParseDuration(o.PhaseTimeout)
	if err != nil {
		duration = 10 * time.Minute
		err = fmt.Errorf("invalid phase timeout duration: %w", err)
	}
	return duration, err
}

// GetDrainTimeout returns the DrainTimeout as a time.Duration.
// Parsing errors return default values along with the error.
func (o ClusterOptions) GetDrainTimeout() (time.Duration, error) {
	if o.DrainTimeout == "" {
		o.DrainTimeout = "20m"
	}
	duration, err := time.ParseDuration(o.DrainTimeout)
	if err != nil {
		duration = 20 * time.Minute
		err = fmt.Errorf("invalid drain timeout duration: %w", err)
	}
	return duration, err
}

// ClusterMaintenanceWindow defines a maintenance window for automatic operations.
type ClusterMaintenanceWindow struct {
	// Enabled indicates whether automatic maintenance operations are enabled for the cluster.
	// +optional
	// +kubebuilder:default=true
	Enabled *bool `json:"enabled,omitempty"`

	// AnnotationsEnabled indicates whether or not the next maintenance window should be annotated on the nodes in the cluster.
	// +optional
	// +kubebuilder:default=true
	AnnotationsEnabled *bool `json:"annotationsEnabled,omitempty"`

	// Cron is a cron expression defining the maintenance window schedule.
	// +required
	Cron string `json:"cron"`

	// Duration is the duration of the maintenance window.
	// +optional
	// +kubebuilder:default="1h"
	Duration string `json:"duration,omitempty"`

	// Timezone is the timezone to use when evaluating the cron schedule.
	// Defaults to UTC if not specified. Must be a valid IANA Time Zone database name
	// (e.g., "America/New_York", "Europe/Berlin", "Asia/Tokyo").
	// +optional
	// +kubebuilder:default="UTC"
	Timezone string `json:"timezone,omitempty"`
}

// IsEnabled returns true if the maintenance window is enabled.
func (mw ClusterMaintenanceWindow) IsEnabled() bool {
	return mw.Enabled == nil || *mw.Enabled
}

// IsAnnotationsEnabled returns true if maintenance window annotations on nodes are enabled.
func (mw ClusterMaintenanceWindow) IsAnnotationsEnabled() bool {
	return mw.AnnotationsEnabled == nil || *mw.AnnotationsEnabled
}

// ClusterArgoCDSecret defines the desired state of the ArgoCD Secret for a Cluster.
type ClusterArgoCDSecret struct {
	// Enabled indicates whether the ArgoCD Secret should be created for the cluster.
	// +optional
	// +kubebuilder:default=true
	Enabled *bool `json:"enabled,omitempty"`

	// Namespace is the namespace in which the ArgoCD Secret should be created.
	// This should be the same namespace where ArgoCD is installed.
	// +required
	Namespace string `json:"namespace"`

	// ClusterNameOverride allows specifying a custom cluster name to be used in ArgoCD.
	// +optional
	ClusterNameOverride string `json:"clusterNameOverride,omitempty"`

	// ExtraLabels are extra labels that should be added to the Argo CD secret, for use with
	// ApplicationSets and similar Argo constructs.
	ExtraLabels map[string]string `json:"extraLabels,omitempty"`
}

// ClusterOperation defines a requested operation on the Cluster.
type ClusterOperation struct {
	// Type of operation to perform across the Cluster.
	// +kubebuilder:validation:Enum=RollingReboot;RollingApply;KubernetesUpgrade;Bootstrap
	// +required
	Type string `json:"type"`
}

// ClusterStatus defines the observed state of Cluster.
type ClusterStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// For Kubernetes API conventions, see:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

	// conditions represent the current state of the Cluster resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// Operation provides details about the current operation being performed on the Cluster.
	// +optional
	Operation *ClusterOperationStatus `json:"operationStatus,omitempty"`

	// NextMaintenanceWindow indicates the start time of the next maintenance window.
	// +optional
	NextMaintenanceWindow metav1.Time `json:"nextMaintenanceWindow,omitzero"`
}

// ClusterOperationStatus defines the status of a Cluster operation.
type ClusterOperationStatus struct {
	ClusterOperation `json:",inline"`

	// Phase indicates the current phase of the operation.
	// +optional
	Phase string `json:"phase,omitempty"`

	// Reason provides a code or short description of why the operation is in its current phase.
	// +optional
	Reason string `json:"reason,omitempty"`

	// Message provides a human-readable message about the operation.
	// +optional
	Message string `json:"message,omitempty"`

	// LastTransitionTime is the last time the operation changed phases.
	// +optional
	LastTransitionTime metav1.Time `json:"lastTransitionTime,omitzero"`

	// SubOperations contains the status of individual Node operations that are part of this Cluster operation.
	// +optional
	SubOperations []ClusterManagedNodeOperationStatus `json:"subOperations"`
}

// ClusterManagedNodeOperationStatus defines the status of a Cluster-managed Node operation.
type ClusterManagedNodeOperationStatus struct {
	NodeOperationStatus `json:",inline"`

	// NodeName is the name of the Node on which the operation is being performed.
	// +required
	NodeName string `json:"nodeName"`
}

// +kubebuilder:object:root=true

// ClusterList contains a list of Cluster
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
