package v1alpha1

// PatchRef defines a reference to a ConfigMap containing a patch.
type PatchRef struct {
	// Name of the ConfigMap containing the patch.
	// +required
	Name string `json:"name"`

	// Key of the patch data in the ConfigMap. Defaults to "patch.yaml" if not specified.
	// +optional
	Key string `json:"key"`

	// Namespace of the ConfigMap containing the patch.
	// Defaults to the same namespace as the Node or Cluster resource if not specified.
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

// PatchHierarchyElement represents a single element in the patch hierarchy, which includes a reference to a patch and the source of that patch.
type PatchHierarchyElement struct {
	PatchRef PatchRef `json:"patchRef,omitempty,omitzero"`

	// where the patchref came from
	Source string `json:"source"`

	// if the patch was synthetic (i.e. generated by the operator), this is where we explain why it was generated
	Synthetic            bool   `json:"synthetic,omitempty"`
	SyntheticExplanation string `json:"syntheticExplanation,omitempty"`
}

// PatchHierarchy explains how the effective config came to be.
type PatchHierarchy []PatchHierarchyElement
