//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(ClusterOperation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterArgoCDSecret) DeepCopyInto(out *ClusterArgoCDSecret) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExtraLabels != nil {
		in, out := &in.ExtraLabels, &out.ExtraLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterArgoCDSecret.
func (in *ClusterArgoCDSecret) DeepCopy() *ClusterArgoCDSecret {
	if in == nil {
		return nil
	}
	out := new(ClusterArgoCDSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMaintenanceWindow) DeepCopyInto(out *ClusterMaintenanceWindow) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AnnotationsEnabled != nil {
		in, out := &in.AnnotationsEnabled, &out.AnnotationsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMaintenanceWindow.
func (in *ClusterMaintenanceWindow) DeepCopy() *ClusterMaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(ClusterMaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagedNodeOperationStatus) DeepCopyInto(out *ClusterManagedNodeOperationStatus) {
	*out = *in
	in.NodeOperationStatus.DeepCopyInto(&out.NodeOperationStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagedNodeOperationStatus.
func (in *ClusterManagedNodeOperationStatus) DeepCopy() *ClusterManagedNodeOperationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterManagedNodeOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperation) DeepCopyInto(out *ClusterOperation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperation.
func (in *ClusterOperation) DeepCopy() *ClusterOperation {
	if in == nil {
		return nil
	}
	out := new(ClusterOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperationStatus) DeepCopyInto(out *ClusterOperationStatus) {
	*out = *in
	out.ClusterOperation = in.ClusterOperation
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	if in.SubOperations != nil {
		in, out := &in.SubOperations, &out.SubOperations
		*out = make([]ClusterManagedNodeOperationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperationStatus.
func (in *ClusterOperationStatus) DeepCopy() *ClusterOperationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOptions) DeepCopyInto(out *ClusterOptions) {
	*out = *in
	in.MaintenanceWindow.DeepCopyInto(&out.MaintenanceWindow)
	in.ArgoCDSecret.DeepCopyInto(&out.ArgoCDSecret)
	if in.AutoBootstrap != nil {
		in, out := &in.AutoBootstrap, &out.AutoBootstrap
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOptions.
func (in *ClusterOptions) DeepCopy() *ClusterOptions {
	if in == nil {
		return nil
	}
	out := new(ClusterOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ControlPlanePatches != nil {
		in, out := &in.ControlPlanePatches, &out.ControlPlanePatches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkerPatches != nil {
		in, out := &in.WorkerPatches, &out.WorkerPatches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PatchRefs != nil {
		in, out := &in.PatchRefs, &out.PatchRefs
		*out = make([]PatchRef, len(*in))
		copy(*out, *in)
	}
	if in.ControlPlanePatchRefs != nil {
		in, out := &in.ControlPlanePatchRefs, &out.ControlPlanePatchRefs
		*out = make([]PatchRef, len(*in))
		copy(*out, *in)
	}
	if in.WorkerPatchRefs != nil {
		in, out := &in.WorkerPatchRefs, &out.WorkerPatchRefs
		*out = make([]PatchRef, len(*in))
		copy(*out, *in)
	}
	in.Options.DeepCopyInto(&out.Options)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(ClusterOperationStatus)
		(*in).DeepCopyInto(*out)
	}
	in.NextMaintenanceWindow.DeepCopyInto(&out.NextMaintenanceWindow)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesComponentUpgradeOptions) DeepCopyInto(out *KubernetesComponentUpgradeOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesComponentUpgradeOptions.
func (in *KubernetesComponentUpgradeOptions) DeepCopy() *KubernetesComponentUpgradeOptions {
	if in == nil {
		return nil
	}
	out := new(KubernetesComponentUpgradeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesVersions) DeepCopyInto(out *KubernetesVersions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesVersions.
func (in *KubernetesVersions) DeepCopy() *KubernetesVersions {
	if in == nil {
		return nil
	}
	out := new(KubernetesVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Node) DeepCopyInto(out *Node) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(NodeOperation)
		(*in).DeepCopyInto(*out)
	}
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Node.
func (in *Node) DeepCopy() *Node {
	if in == nil {
		return nil
	}
	out := new(Node)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Node) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeList) DeepCopyInto(out *NodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Node, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeList.
func (in *NodeList) DeepCopy() *NodeList {
	if in == nil {
		return nil
	}
	out := new(NodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeOperation) DeepCopyInto(out *NodeOperation) {
	*out = *in
	out.Options = in.Options
	out.Provision = in.Provision
	in.Reset.DeepCopyInto(&out.Reset)
	out.KubernetesComponentUpgrade = in.KubernetesComponentUpgrade
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeOperation.
func (in *NodeOperation) DeepCopy() *NodeOperation {
	if in == nil {
		return nil
	}
	out := new(NodeOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeOperationOptions) DeepCopyInto(out *NodeOperationOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeOperationOptions.
func (in *NodeOperationOptions) DeepCopy() *NodeOperationOptions {
	if in == nil {
		return nil
	}
	out := new(NodeOperationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeOperationStatus) DeepCopyInto(out *NodeOperationStatus) {
	*out = *in
	in.NodeOperation.DeepCopyInto(&out.NodeOperation)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeOperationStatus.
func (in *NodeOperationStatus) DeepCopy() *NodeOperationStatus {
	if in == nil {
		return nil
	}
	out := new(NodeOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSpec) DeepCopyInto(out *NodeSpec) {
	*out = *in
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PatchRefs != nil {
		in, out := &in.PatchRefs, &out.PatchRefs
		*out = make([]PatchRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSpec.
func (in *NodeSpec) DeepCopy() *NodeSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(NodeOperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.KubernetesVersions != nil {
		in, out := &in.KubernetesVersions, &out.KubernetesVersions
		*out = new(KubernetesVersions)
		**out = **in
	}
	if in.PatchHierarchy != nil {
		in, out := &in.PatchHierarchy, &out.PatchHierarchy
		*out = make(PatchHierarchy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in PatchHierarchy) DeepCopyInto(out *PatchHierarchy) {
	{
		in := &in
		*out = make(PatchHierarchy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchHierarchy.
func (in PatchHierarchy) DeepCopy() PatchHierarchy {
	if in == nil {
		return nil
	}
	out := new(PatchHierarchy)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchHierarchyElement) DeepCopyInto(out *PatchHierarchyElement) {
	*out = *in
	out.PatchRef = in.PatchRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchHierarchyElement.
func (in *PatchHierarchyElement) DeepCopy() *PatchHierarchyElement {
	if in == nil {
		return nil
	}
	out := new(PatchHierarchyElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchRef) DeepCopyInto(out *PatchRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchRef.
func (in *PatchRef) DeepCopy() *PatchRef {
	if in == nil {
		return nil
	}
	out := new(PatchRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionOperationOptions) DeepCopyInto(out *ProvisionOperationOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionOperationOptions.
func (in *ProvisionOperationOptions) DeepCopy() *ProvisionOperationOptions {
	if in == nil {
		return nil
	}
	out := new(ProvisionOperationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResetOperationOptions) DeepCopyInto(out *ResetOperationOptions) {
	*out = *in
	if in.Graceful != nil {
		in, out := &in.Graceful, &out.Graceful
		*out = new(bool)
		**out = **in
	}
	if in.SystemLabelsToWipe != nil {
		in, out := &in.SystemLabelsToWipe, &out.SystemLabelsToWipe
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UserDisksToWipe != nil {
		in, out := &in.UserDisksToWipe, &out.UserDisksToWipe
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResetOperationOptions.
func (in *ResetOperationOptions) DeepCopy() *ResetOperationOptions {
	if in == nil {
		return nil
	}
	out := new(ResetOperationOptions)
	in.DeepCopyInto(out)
	return out
}
